### ISSUE TITLE
REST Services for Email Verification

### ISSUE THREAD

**Issue by herau** [herau/diy-project#14]
1. [x] Generate a token for the user and persist it
2. [x] Send an email with an embedded link that includes the token to the user
3. [x] User clicks on the link which takes them to a static page
4. [x] The static page calls the API passing the token
5. [x] If the token is valid the user is set to verified

follow requirement in #5

**Comment by VPusher** [comment]
This breaks the app on my side (accessing the root page):
```
WARN 50362 --- [nio-8080-exec-1] .w.s.m.s.DefaultHandlerExceptionResolver : Handler execution resulted in exception: Required String parameter 'token' is not present
```

Did you forgot to provide a configuration ?

**Comment by herau** [comment]
the generated link (in the mail) : `http://domain.com/token/{token}`
the POST API to set the user password (and make the user valid) : `http://domain.com/api/users/token/{token}` with a body like :
```
{
   "password": "value"
}
```
