### ISSUE TITLE
Hot swapping

### ISSUE THREAD

**Issue by herau** [herau/diy-project#6]
Reload static content

**Comment by herau** [comment]
@VPusher @Thinkedou @pfs31110 Automatic Reload static content is available for resources in `src/main/resources/static` when you use either an IDE or Maven.

For Maven (maybe more for the frontend guys), you just need to launch the application with a maven command : 
`mvn spring-boot:run `. Then you can modify any resources and just reload the page.

__Prerequisite:__

* Java 8
* Maven installed and configured for the right java version (if you have multiple jdk on your laptop)
 * [Download Maven](https://maven.apache.org/download.cgi)
 * [Install Maven](https://maven.apache.org/install.html)

**Comment by VPusher** [comment]
Just wondering about using maven spring boot plugin instead of Docker image for dev. I surprisingly discovered the plugin was already there. Great !
